import { images } from "./cardImgs";

export const cards = {
  Green: [
    {
      index: 0,
      title: "Связывание углерода",
      description:
        "Связывание углерода — это процесс, в ходе которого углеродные атомы соединяются между собой или с другими элементами, образуя химические соединения. В биологических системах связывание углерода имеет важное значение, поскольку оно лежит в основе жизненно важных процессов, таких как фотосинтез и клеточное дыхание. В ходе фотосинтеза растения захватывают углекислый газ из атмосферы и, используя солнечную энергию, преобразуют его в органические молекулы, такие как углеводы. Эти молекулы служат источником энергии для большинства живых существ.",
      link: "https://search.app/VePfKaJAwjYRozsM7",
      image: images.Green.carbonSeq,
    },
    {
      index: 1,
      title: "Глобальное потепление",
      description: "Глобальное потепление",
      link: "https://search.app/xXaWBqBmVUwJikXc9",
      image: images.Green.globalWarming,
    },
    {
      index: 2,
      title: "Качество и доступность среды обитания",
      description: "Качество и доступность среды обитания",
      link: "https://search.app/2aWfsW4YhZRGbd6UA",
      image: images.Green.habitat,
    },
    {
      index: 3,
      title: "Коммерческое рыболовство",
      description: "Коммерческое рыболовство",
      link: "https://search.app/CWyYe4kaJtaShWyR8",
      image: images.Green.climateChange,
    },
    {
      index: 4,
      title: "Спортивная рыбалка",
      description: "Спортивная рыбалка",
      link: "https://www.craiyon.com/image/2h8pJ0zuQD6mawpHOjH3zw",
      image: images.Green.sportFishing,
    },
    {
      index: 5,
      title: "Прогулочное катание на лодках",
      description: "Прогулочное катание на лодках",
      link: "https://www.craiyon.com/image/lMkDXUSNTuuwRuBOoFBeug",
      image: images.Green.recreation,
    },
    {
      index: 6,
      title: "Производство дикого риса",
      description: "Производство дикого риса",
      link: "https://search.app/5ANeLspNrfGqRovKA",
      image: images.Green.wildRice,
    },
    {
      index: 7,
      title: "Урожайность озимой пшеницы",
      description: "Урожайность озимой пшеницы",
      link: "https://www.craiyon.com/image/-bcetbHzQheAf0vSOaLmpQ",
      image: images.Green.yieldRice,
    },
    {
      index: 8,
      title: "Риск лесного пожара",
      description: "Риск лесного пожара",
      link: "",
      image: images.Green.wildFire,
    },
    {
      index: 9,
      title: "Деградация среды обитания",
      description:
        "Деградация среды обитания за счет вырубки лесов в сельской горной местности",
      link: "https://www.craiyon.com/image/riRK9KyZREqUyhEEWcf_UQ",
      image: images.Green.deforestation,
    },
  ],
  Violet: [
    {
      index: 0,
      title: "Разведение крупного рогатого скота",
      description:
        "Средства к существованию на основе разведения крупного рогатого скота",
      link: "https://search.app/v3gP3M1KYo56szXT8",
      image: images.Violet.cattleLivelihood,
    },
    {
      index: 1,
      title: "Растениеводство и мелкое скотоводство",
      description:
        "Средства к существованию, основанные на растениеводстве и мелком скотоводстве",
      link: "https://search.app/1tYx1f76uoSNkcho9",
      image: images.Violet.cropCattleLivelihood,
    },
    {
      index: 2,
      title: "Нефермерские средства к существованию",
      description: "Нефермерские средства к существованию в сельской местности",
      link: "https://search.app/SeUHtX8h8zrJR51r5",
      image: images.Violet.nonFarmLivelihood,
    },
    {
      index: 3,
      title: "Стабильность предприятия",
      description: "Стабильность предприятия",
      link: "https://search.app/S1XZLAQugrctiDJe9",
      image: images.Violet.enterpriseStability,
    },
    {
      index: 4,
      title: "Надежность и безопасность автомобиля",
      description: "Надежность и безопасность автомобиля",
      link: "https://www.craiyon.com/image/B5R28A_3RZKJTn4WByAAvw",
      image: images.Violet.vehilce,
    },
    {
      index: 5,
      title: "Доля рынка",
      description: "Увеличение доли рынка компании за счет диверсификации",
      link: "https://search.app/1adA5qcaNaSWsvBHA",
      image: images.Violet.marketShare,
    },
    {
      index: 6,
      title: "Знания персонала",
      description: "Знания персонала",
      link: "https://search.app/b6cvsj1J5bs7hnGw6",
      image: images.Violet.staffKnowledge,
    },
    {
      index: 7,
      title: "Производственные затраты",
      description: "Производственные затраты",
      link: "https://www.craiyon.com/image/SqgBjmGdRJClAq5mhav3bA",
      image: images.Violet.executionCost,
    },
    {
      index: 8,
      title: "Клинический риск",
      description: "Клинический риск в администрировании лекарств",
      link: "https://www.craiyon.com/image/2U4cGPxeTn-tqFstIIAztA",
      image: images.Violet.clinicalRisk,
    },
    {
      index: 9,
      title: "Выбор научной конференции",
      description: "Выбор научной конференции",
      link: "https://www.craiyon.com/image/5sG-Mkv2QVW-zAe2TRZblA",
      image: images.Violet.conferenceSelection,
    },
    {
      index: 10,
      title: "Монтаж трубопроводов",
      description: "Монтаж трубопроводов",
      link: "https://www.craiyon.com/image/ATspx3rPR-ibVF982ERPsQ",
      image: images.Violet.pipingInstallation,
    },
    {
      index: 11,
      title: "Энергетический переход",
      description: "Энергетический переход",
      link: "https://search.app/mkg6Ccuhs2v9xcqy8",
      image: images.Violet.energyTransition,
    },
  ],
  Orange: [
    {
      index: 0,
      title: "Преступление и наказание",
      description: "Преступление и наказание",
      link: "https://www.craiyon.com/image/f2TkYJ46TqKyyl0Rt_GJ3g",
      image: images.Orange.crime,
    },
    {
      index: 1,
      title: "Кубинский ракетный кризис",
      description: "Кубинский ракетный кризис",
      link: "https://search.app/Yjx1o9gNj5d2jzaZ7",
      image: images.Orange.cuban,
    },
    {
      index: 2,
      title: "Финансовый кризис в Малайзии",
      description: "Финансовый кризис спекулятивных инвестиций",
      link: "https://search.app/Wy8Y3erT3fLKqgEB6",
      image: images.Orange.malaysia,
    },
    {
      index: 3,
      title: "Финансовый кризис в Южной Кореи",
      description: "Финансовый кризис промышленного развития",
      link: "https://search.app/Lf1xh2KB8mMmD1tT8",
      image: images.Orange.korea,
    },
    {
      index: 4,
      title: "Влияние ИТ на расходы",
      description: "Влияние ИТ на расходы по экономическому развитию",
      link: "https://www.craiyon.com/image/k_54MUGrRfCyrtE5GLuzJA",
      image: images.Orange.itImpact,
    },
    {
      index: 5,
      title: "Бездомность",
      description: "Бездомность",
      link: "https://www.craiyon.com/image/OUFGuuZ8RNuZ0gh-BvYh_Q",
      image: images.Orange.homelessness,
    },
  ],
};

export const cardcreds = {
  Green: {
    name: "Green",
    desc: "Жизнь в окружении природы / Сбережение природы / Качество среды обитания.",
    src: images.Green.greenImage,
    color: "#52ffbd",
  },
  Orange: {
    name: "Orange",
    desc: "Совершенное общественное устройство / Баланс социальных факторов / Настройка институционального комплекса.",
    src: images.Orange.orangeImage,
    color: "#ff8b2b",
  },
  Violet: {
    name: "Violet",
    desc: "Устойчивое жизнеобеспечение / Сбережение природы / Надежность и безопасность.",
    src: images.Violet.violetImage,
    color: "#eea8ff",
  },
};
